### ISSUE TITLE
Write file with extension `.t.sol` rather than `.sol`

### ISSUE THREAD

**Issue by jparklev** [alexfertel/bulloak#4]
As is usually expected in the case of forge tests :)

**Comment by alexfertel** [comment]
Thank you for opening an issue, good ser!

> Write file with extension .t.sol rather than .sol

Yes! This is a corollary of https://github.com/alexfertel/bulloak/issues/1. Since every `.tree` file starts with an output filename, `.t.sol` can be specified there. This way, we don't force a convention onto the user, who can freely choose their pain.

Closing because https://github.com/alexfertel/bulloak/issues/1 solves this!

**Comment by alexfertel** [comment]
@jparklev https://github.com/alexfertel/bulloak/issues/1#issuecomment-1673895532

**Comment by jparklev** [comment]
What good service, thank u mr alex
