### ISSUE TITLE
Commit Cargo.lock file

### ISSUE THREAD

**Issue by beeb** [alexfertel/bulloak#48]
I would be nice to commit your Cargo.lock file, as [suggested by the Cargo team](https://blog.rust-lang.org/2023/08/29/committing-lockfiles.html). This also would help with creating a nix derivation for this utility, which requires a Cargo.lock file for reproducibility.

**Comment by alexfertel** [comment]
Yes! I remember reading that but forgot to do it. Thanks for opening this issue 👍🏻

**Comment by alexfertel** [comment]
>  It would be also very useful to tag versions in git with v0.x.x tags.

I had been doing that, but was also forgetting to push the tags 🤦🏻‍♂️ Pushed both the tags and the Cargo.lock just now. Thanks for pointing that out!

> I would be happy to publish the package to the nixpkgs repo once that is done!

That would be very awesome 🙏🏻

**Comment by alexfertel** [comment]
Closing since https://github.com/alexfertel/bulloak/commit/ac4fe7d4a94dcc249f359451ff05d0a05fdc2ac5 resolves this.

**Comment by alexfertel** [comment]
Hey @beeb, I published a new version! v0.5.4 includes the `Cargo.lock`. However, I wanted to check with you one thing. Currently, I change the package version in the commit right after I add a tag, i.e. I end up with the following:
![Screenshot 2023-11-16 at 17 50 38](https://github.com/alexfertel/bulloak/assets/22298999/0df4b8cf-047b-449c-b82d-541f2b065759)

where, `chore(v0.5.4)` is the commit updating the package version, which in turn updates the `Cargo.lock` and `fix(scaffold)` is the tag `v0.5.4`.

Would that be an issue for the nix derivation? If yes, I'll figure out how to do everything at once (currently doing this because I'm using git-cliff to generate the changelogs).

**Comment by beeb** [comment]
Thanks for the quick release! Yeah the way you are doing it is indeed a problem. If I check out the tag I will not see the correct information in the Cargo files. It would be no problem if the tag came after the changes in Cargo files (as long as they didn't change in the mean time) but it's a problem if the tag is before.

**Comment by alexfertel** [comment]
Hmmm, I see. Okay, I force-pushed (should be fine, since it's been live for just an hour) the tag to point to the correct commit and will figure out a new flow for the next release. Lmk if it works well for you this way.

**Comment by beeb** [comment]
There you go https://github.com/NixOS/nixpkgs/pull/268113
